### ISSUE TITLE
chapter5に取り組んでいる最中に、k get pod した際にex1の無数のpodが表示された。

### ISSUE THREAD

**Issue by HirokiYamagami** [n-guitar/k8s-bootcamp#34]
# 環境
- Mac
- OSS(Kubeadm)
- k8s version 1.22

# 質問内容
chapter5のex3に取り組んでいる最中で、k get pod した際にex1の無数のpodが表示されました。

vagrant@master-node:~$ kubectl get pods
NAME                       READY   STATUS        RESTARTS   AGE
ex1-pod-798799984f-22c85   0/1     Terminating   0          61m
ex1-pod-798799984f-24ckd   0/1     Terminating   0          57m
ex1-pod-798799984f-24hgj   0/1     Terminating   0          59m
ex1-pod-798799984f-24hvc   0/1     Terminating   0          58m
ex1-pod-798799984f-255fl   0/1     Terminating   0          61m
ex1-pod-798799984f-256dz   0/1     Terminating   0          55m
…(以下多すぎるため中略)

どこか手順を間違えてしまって発生したかと思うのですが、原因がよく分からないため、もし心当たりなどがありましたら教えていただければと思います。

(podは全て
 k get pod | awk '/ex1-pod-*/{print $1}' |xargs kubectl delete pod --force --grace-period=0 　のコマンドで消しました)

**Comment by HirokiYamagami** [comment]
replica数は2で実行して、ex1は普通にできていたのですが、その後ex2に取り組んだ後にex3をやっている最中に、 k get podすると上記のように無数のex1関連のpodがterminatingの状態で存在していた、という感じになります。

手順としては以下の通りです。

1 ex1に取り組む。
(結果だけ記載します) 
vagrant@master-node:~$k get pods -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP              NODE            NOMINATED NODE   READINESS GATES
ex1-pod-798799984f-jp8pn   1/1     Running   0          6s    10.244.87.254   worker-node01   <none>           <none>
ex1-pod-798799984f-s6n9v   1/1     Running   0          6s    10.244.87.247   worker-node01   <none>           <none>

2 そのままex3を実行する。
vagrant@master-node:~$ k get pods -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP              NODE            NOMINATED NODE   READINESS GATES
ex1-pod-798799984f-jp8pn   1/1     Running   0          23s   10.244.87.254   worker-node01   <none>           <none>
ex1-pod-798799984f-s6n9v   1/1     Running   0          23s   10.244.87.247   worker-node01   <none>           <none>
ex3-pod-6f4ff67497-dg7vd   1/1     Running   0          2s    10.244.87.249   worker-node01   <none>           <none>
ex3-pod-6f4ff67497-xzrqr   1/1     Running   0          2s    10.244.158.20   worker-node02   <none>           <none>

3 k taint nodes worker-node01 cpu=lowspec:NoExecute　でtaintする

4 k get -o wide で以下のような状況になる。

NAME                       READY   STATUS        RESTARTS   AGE    IP              NODE            NOMINATED NODE   READINESS GATES
ex1-pod-798799984f-296h7   0/1     Terminating   0          1s     <none>          worker-node01   <none>           <none>
ex1-pod-798799984f-4c5lf   0/1     Terminating   0          1s     <none>          worker-node01   <none>           <none>
ex1-pod-798799984f-4j9tx   0/1     Terminating   0          3s     <none>          worker-node01   <none>           <none>
ex1-pod-798799984f-4l8ng   0/1     Terminating   0          1s     <none>          worker-node01   <none>           <none>
ex1-pod-798799984f-5hjbh   0/1     Terminating   0          4s     <none>          worker-node01   <none>           <none>
ex1-pod-798799984f-6lh95   0/1     Terminating   0          4s     <none>          worker-node01   <none>           <none>
ex1-pod-798799984f-7hdpb   0/1     Terminating   0          4s     <none>          worker-node01   <none>           <none>
(略)

**Comment by n-guitar** [comment]
@HirokiYamagami 
まさにそれがex3-2で問われている内容になります。
NoExecuteというオプションがどのような影響をPodに及ぼすか考えていただければと思います。
